config/routes.rb
Rails.application.routes.draw do
 

   root 'pages#home'
   get '/workwithus' => 'pages#contact'
   get '/about' => 'pages#about'
   get '/testimonials' => 'pages#testimonials'
   get '/stationary' => 'pages#stationary'
   get '/theschoolyard' => 'pages#schoolyard'
   get '/usbs' => 'pages#usb'
   get '/winebags' => 'pages#winebag'
   get '/bags' => 'pages#bag'
   resources :categories
   resources :products
    mount Refinery::Core::Engine, at: Refinery::Core.mounted_path

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	validates :category, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_attached_file :image, :styles => { :medium => "200x>", :thumb => "100x100>" }, :default_url => "/images/default.jpg"
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	validates :title, presence: true
	validates :price, presence: true
	validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, except: [:index, :new, :create]

	def index
		@categories = Category.all

	end

	def show
		
	
	end

	def new
		@category = Category.new
	end

	def create
		#require 'pry';binding.pry
		@category = Category.new(category_params)
		if @category.save
			flash[:success] = 'Category has been created'
			redirect_to @category
		else
			flash[:danger] = 'Category has not been created'
			render :new
		end
		
	end

	def edit
		
	end

	def update
		
		if @category.update(category_params)
			flash[:success] = 'Category has been updated'
			redirect_to @category
		else
			flash[:danger] = 'Category has not been updated'
			render :edit
		end
	end

	def destroy
		if @category.destroy
			flash[:success] = 'Category has been deleted'
			redirect_to categories_path
		end
	end


	private

	def category_params
		params.require(:category).permit(:category)
		
	end

	def set_category
		#factored this line out of the following methods - show, edit, update, destroy
		#this method runs in the before_action
		@category = Category.find(params[:id])
	end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def contact
	end

	def about
	end

	def testimonials
	end

	def schoolyard
	end

	def usb
	end

	def winebag
	end

	def bag
	end

	def stationary
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	before_action :set_product, except: [:index, :new, :create]

	def index
		@products = Product.all

	end

	def show
		
		#require 'pry';binding.pry
	end

	def new
		@product = Product.new
	end

	def create
		#require 'pry';binding.pry
		@product = Product.new(product_params)
		if @product.save
			flash[:success] = 'Product has been created'
			redirect_to @product
		else
			flash[:danger] = 'Product has not been created'
			render :new
		end
		
	end

	def edit
		
	end

	def update
		
		if @product.update(product_params)
			flash[:success] = 'Product has been updated'
			redirect_to @product
		else
			flash[:danger] = 'Product has not been updated'
			render :edit
		end
	end

	def destroy
		if @product.destroy
			flash[:success] = 'Product has been deleted'
			redirect_to products_path
		end
	end


	private

	def product_params
		params.require(:product).permit(:title, :price, :description, :image)
		
	end

	def set_product
		#factored this line out of the following methods - show, edit, update, destroy
		#this method runs in the before_action
		@product = Product.find(params[:id])
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= simple_form_for(@category, :html => {class: "form-horizontal"}) do |f| %>
	
	<div class="form-group">
		<label for="name" class="control-label col-sm-3">Category Name</label>
		<div class="col-sm-9">
			<%= f.input :category_name, class: 'form-control', hide_label: true %>
		</div>
	</div>

	<div class="form-group actions control-group">
		<div class="col-sm-offset-3">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>

<% end %>

app/views/categories/edit.html.erb
<h1>categories#edit</h1>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/categories/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Category</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.category, category %></td>
 		
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h4><%= link_to 'New Category', new_category_path(@category) %> </h4>

app/views/categories/new.html.erb
<h1>categories#new</h1>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/categories/show.html.erb
<h1>categories#show</h1>

 
  <h2><%= @category.category  %></h2>
  <h4><%= link_to 'Edit', edit_category_path(@category) %> |
		  <%= link_to 'Delete', category_path(@category), method: :delete, data: { confirm: 'Are you sure?' } %> 
		  | <%= link_to 'Back', categories_path %>
	</h4>

app/views/layouts/_carousel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators dot nav at bottom-->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1" class=""></li>
        <li data-target="#myCarousel" data-slide-to="2" class=""></li>
      </ol>

      <!-- wrapper for slides -->
      <div class="carousel-inner" role="listbox">
        <div class="item active">
           
          <%= image_tag("banner1.jpg", alt: 'The Schoolyard', class: "first-slide") %>

          <div class="container">
            <div class="carousel-caption">
              <h1>The Schoolyard</h1>
              <p>The Schoolyard</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
        <div class="item">
           <%= image_tag("stock2.jpg", alt: 'Secoond Slide', class: "second-slide") %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Hear what our customers have to say</h1>
              <p>Paragraph? See our work? Corporate gifts are a great way for you to keep your logo and
brand name in front of your target audience.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
            </div>
          </div>
        </div>
        <div class="item">
         <%= image_tag("stock3.jpg", alt: 'Third Slide', class: "third-slide") %>
          <div class="container">
            <div class="carousel-caption">
              <h1>Go Green.</h1>
              <p>Going green simply means that you live in harmony with the Earth by making choices and using products in your daily life that support the health of the environment and reduce harm to our planet. Regardless of what you may believe about global warming, climate change and the obviously changing weather patterns all around us, the Earth always benefits from any effort to reduce stress on her ecosystems. By recycling and reusing we reduce the amount of mostly non-biodegradable waste that sits in landfills. Environmentally friendly/ eco-friendly/ nature-friendly products inflict reduced, minimal, or no harm at all, upon ecosystems thus aiding to the long-term health and sustainability of our beloved planet.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
            </div>
          </div>
        </div>
      </div>

      <!-- controls for next and prev buttons -->
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->

app/views/layouts/_footer.html.erb
<section id="footer" class="section footer">
		<div class="container">
			<div class="row animated opacity mar-bot20" data-andown="fadeIn" data-animation="animation">
				<div class="col-sm-12 align-center">
                 			
				</div>
			</div>

			<div class="row align-center copyright">
					<div class="col-sm-12"><p>Copyright &copy; 2015 DreamWorth </p></div>
    
			</div>
		</div>

	</section>
	<a href="#header" class="scrollup"><i class="fa fa-chevron-up"></i></a>	

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
 
      <a class="navbar-brand" href="/">
        <%= image_tag("logo.png", alt: 'DreamWorth Logo', class: "header-logo") %>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">


      <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About Us <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="/testimonials">Our Work</a></li>
          <li><a href="/contact">Contact</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="/about">About Us</a></li>
        </ul>
      </li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
        <ul class="dropdown-menu">

          <li><a href="products.html#bags">Eco-Friendly Bags</a></li>
          <li><a href="products.html#stationary">Pens & Stationary</a></li>
          <li><a href="products.html#usb">USB & Flash Drives</a></li>
          <li><a href="/theschoolyard">The School Yard</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="/products">All Products</a></li>
        </ul>
      </li>
    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DwSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 


</head>
<body>
<%= render 'layouts/header' %> 
<%= yield %>
<% flash.each do |name, msg| %>
	<div class="alert alert- <%= "#{name}" %> ">
		<a href="#" class="close" data-dismiss="alert &#215;"></a>
		<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
<% end %>
<%= render 'layouts/footer' %>

</body>
</html>

app/views/pages/about.html.erb
<div class="page-content"><div class="page-wrapper">
	<section id="section-about" class="section appear clearfix">
		<div class="container">
			<div class="row mar-bot40">
				<div class="col-md-offset-3 col-md-6">
					<div class="section-header">
						<h2 class="section-heading animated" data-animation="bounceInUp">DreamWorth</h2>
						<p>DreamWorth Private Limited is a pioneering business that specializes in supplying eco-friendly commodities to African and global markets. Our products are sourced both locally (Zimbabwe), and internationally. Through extensive research and keen market insights we are able to identify products that have the best fit for the target markets in Africa and beyond. DreamWorth aims to penetrate different sectors of its target markets with innovative, first to market and superior goods.</p>
						<p>DreamWorth Private Limited has been in operation since 2011.</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	
		<section id="section-about" class="section appear clearfix vision">
		<div class="container">
			<div class="row mar-bot40">
				<div class="col-md-offset-3 col-md-6">
					<div class="section-header">
						<h2 class="section-heading animated" data-animation="bounceInUp">Vision</h2>
						<p>To spearhead the supply of inventive, high quality and eco-friendly merchandise to African markets and beyond. </p>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section id="section-about" class="section appear clearfix mission">
		<div class="container">
			<div class="row mar-bot40">
				<div class="col-md-offset-3 col-md-6">
					<div class="section-header">
						<h2 class="section-heading animated" data-animation="bounceInUp">Mission</h2>
						<p>To induce a paradigm shift and inspire a culture of eco-friendliness through unique products, close customer contact and excellent relationships.</p>
					</div>
				</div>
			</div>
		</div>
	</section>


	<!-- about -->
	<section id="section-about" class="section appear clearfix values">
	<div class="container">

			<div class="row mar-bot40">
				<div class="col-md-offset-3 col-md-6">
					<div class="section-header">
						<h2 class="section-heading animated" data-animation="bounceInUp">Values</h2>
						
					</div>
				</div>
			</div>

				<div class="row align-center mar-bot40">
					<div class="col-md-3">
						<div class="team-member">
							
							<div class="team-detail">
								<h4>Professionalism</h4>
								<span>To build long-term, professional relationships with all stakeholders.</span>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="team-member">
							
							<div class="team-detail">
								<h4>Distinctiveness</h4>
								<span>To break traditional market barriers (breaking through the "usual" market forces and conventional way of doing business). </span>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="team-member">
							
							<div class="team-detail">
							<h4>Integrity</h4>
								<span>To be a dependable and trusted business partner.</span>
							</div>
						</div>
					</div>
					<div class="col-md-3">
						<div class="team-member">
							
							<div class="team-detail">
							<h4>Client Focus</h4>
								<span>To provide tailor-made products to meet specific customer needs.</span>

							</div>
						</div>
					</div>
				</div>
					
	</div>
	</section>

			
<!-- about -->
<section id="section-about" class="section appear clearfix team">
<div class="container">

		<div class="row mar-bot40">
			<div class="col-md-offset-3 col-md-6">
				<div class="section-header">
					<h2 class="section-heading animated" data-animation="bounceInUp">The Dream Team</h2>
					
				</div>
			</div>
		</div>

			<div class="row align-center mar-bot40">
				<div class="col-md-3">
					<div class="team-member">
						
						<div class="team-detail">
							<h4>Director| Kudzaishe E. Mutsaka</h4>
							<span>Master of Science in Clinical Biochemistry University of Zimbabwe</span>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="team-member">
						
						<div class="team-detail">
							<h4>Director| Brian Mataruka</h4>
							<span>Bachelor of Laws Honours Degree University of Zimbabwe </span>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="team-member">
						
						<div class="team-detail">
						<h4>Finance| Steven Alphine</h4>
							<span>Bachelor of Commerce Deakin University</span>
						</div>
					</div>
				</div>
				<div class="col-md-3">
					<div class="team-member">
						
						<div class="team-detail">
						<h4>Managing Director| Munya Dzumbira</h4>
							<span>Bachelor of Business &amp; Commerce</span>
							<span>Marketing and Management (Honors) Monash University, Australia</span>
						</div>
					</div>
				</div>
			</div>
				
</div>
</section>
		<!-- /about -->

</div>
</div>
	  
	

app/views/pages/contact.html.erb
<h1>pages#contact</h1>

app/views/pages/home.html.erb
<%= render 'layouts/carousel' %>

<div class="container-fluid">
  <div class="row present home-about">
    <div class="col-md-10 col-md-offset-1"> 
      <h2 class="present">DreamWorth</h2>
      <p class="lead">Dreamworth is dedicated to maintaining your brand’s integrity and delivering your order on time and on budget. Whether your company is large or small, our team of creative experts is here to help you develop the best marketing solution. This means you will find the perfect promotional products to fit your company’s advertising needs. Our topnotch customer service is unmatched in the industry, keeping you our top priority. We can offer you a wide variety of custom promotional items at competitive prices. You will find thousands of products available, with new products added daily so your brand can keep up with the latest trends.</p>
      <!-- READ MORE LINK TO ABOUT PAGE -->
    </div>
  </div>


  <section id="section-works" class="section appear clearfix">
    <div class="container">

      <div class="row mar-bot40">
        <div class="col-md-offset-3 col-md-6">
          <div class="section-header">
            <h2 class="section-heading animated" data-animation="bounceInUp">Products</h2>
            <p>Our unique range of eco-friendly corporate gifts and promotional items include bags, pens, stationary, USB flash drives, and more.</p>
          </div>
        </div>
      </div>

      <!-- RESIZE IMAGES 360 x 240 px -->              
      <div class="col-md-12">
        <div class="row">
          <div class="portfolio-items isotopeWrapper clearfix" id="3">

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("Card_Bag.JPG", alt: 'Generic placeholder image' ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Eco-Friendly Bags</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("Card_WineBag.JPG", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Eco-Friendly Wine Bags</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>


            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>

            <article class="col-md-4 isotopeItem webdesign">
              <div class="portfolio-item">
                <%= image_tag("stock1.jpg", alt: 'Generic placeholder image', ) %>

                <div class="portfolio-desc align-center">
                  <div class="folio-info">
                    <h5><a href="#">Portfolio name</a></h5>
                    <a href="img/portfolio/img1.jpg" class="fancybox"><i class="fa fa-plus fa-2x"></i></a>
                  </div>                      
                </div>
              </div>
            </article>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>

<section>
  <div class="container-fluid">
    <div class="row present home-about">
      <div class="col-md-10 col-md-offset-1"> 

        <p class="lead">Research shows that the correct promotional products can provide a higher ROI (return on investment) than other forms of advertising. Corporate gifts are a great way for you to keep your logo and brand name in front of your target audience. We offer a great range of corporate gifts that can all be personalized for any business at competitive prices.</p>
        <p class="lead">We provide our clients with a wide range of merchandising options while raising the bar in the corporate gifts and branded goods arena. Our professional approach results in a worry-free and enjoyable customer experience. If you are looking for branded merchandising solutions that are dynamic, creative, impactful, timeous, and within budget, then we are your partner.</p>

      </div>
    </div>

  </section>

app/views/pages/schoolyard.html.erb
<h1>Schoolyard</h1>

app/views/pages/testimonials.html.erb
<div class="page-wrapper">
		<h1> Client list</h1>
	

	<div class="catalogue"> 

	<!-- ROW 1 -->
	<div class="row">
		<div class="col-md-4">	
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
	   		 	<img src="images/b.jpg" width="150" height="100" alt="">
				<li> Afrasia Kingdom Bank.</li>
			</a>
		</div>

		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
			    <img src="images/b.jpg" width="150" height="100" alt="">
				<li> Cancer Association of Zimbabwe.</li>
				</a>
		</div>

		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
			    <img src="images/b.jpg" width="150" height="100" alt="">
				<li> Covenant Women Ministries.</li>
				</a>
		</div>	
	</div>	

	<!-- ROW 2 -->

	<div class="row">

		<div class="col-md-4">
				<a href="images/b.jpg?theme=metro" class="speedo-popup">
				    <img src="images/b.jpg" width="150" height="100" alt="">
					<li> IDA Zimbabwe.</li>
					</a>
		</div>

		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
			    <img src="images/b.jpg" width="150" height="100" alt="">
				<li> The United Methodist Church of Zimbabwe.</li>
				</a>
		</div>
		
		<div class="col-md-4">	
			<a href="images/f.jpg?theme=metro" class="speedo-popup">
			    <img src="images/f.jpg" width="150" height="100" alt="">
				<li> TOPS Liquor.</li>
				</a>
		</div>
	</div>
	<!-- ROW 3 -->

	<div class="row">
		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
			    <img src="images/b.jpg" width="150" height="100" alt="">
				<li> Spar Corporate Group.</li>
				</a>
		</div>

		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
			    <img src="images/b.jpg" width="150" height="100" alt="">
				<li> Heartfelt International Ministries.</li>
				</a>
		</div>
		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
		    <img src="images/b.jpg" width="150" height="100" alt="">
			<li> Nguni &amp; Ngwenya.</li>
			</a>
		</div>	
		

	</div>

	<!-- ROW 4 -->

	<div class="row">
		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
		    <img src="images/b.jpg" width="150" height="100" alt="">
			<li> Phoebe's Made with Love.</li>
			</a>
		</div>

		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
		    <img src="images/b.jpg" width="150" height="100" alt="">
			<li> Telecel.</li>
			</a>
		</div>
		<div class="col-md-4">
			<a href="images/b.jpg?theme=metro" class="speedo-popup">
		    <img src="images/b.jpg" width="150" height="100" alt="">
			<li> UNWTO.</li>
			</a>
		</div>	

	</div>

</div>

<h1> Testimonials</h1>

<blockquote class="testimonial">
<p>We recommend DreamWorth Pvt Ltd unreservedly to any organization that may wish to do business with them. Their service and delivery times are professional and of a high standard, something this country could do with more of.
</p>
</blockquote>
<div class="arrow-down"></div>
<p class="testimonial-author">Junior Mavu|<span>Cancer Association of Zimbabwe</span></p>
<br>

<br>
<blockquote class="testimonial">
<p>Dreamworth Private Limited is a registered premier service provider of corporate gifts to AfrAsia Kingdom Zimbabwe Limited. We therefore recommend Dreamworth Pvt Ltd unreservedly to any organization that may wish to do business with them.
</p>
</blockquote>
<div class="arrow-down"></div>
<p class="testimonial-author">Afrasia Kingdom |<span>Zimbabwe Marketing Department</span></p>
<br>

 </div>

app/views/products/_form.html.erb
<%= simple_form_for(@product, :html => {class: "form-horizontal"}) do |f| %>
	
	<div class="form-group">
		<label for="title" class="control-label col-sm-3">Title</label>
		<div class="col-sm-9">
			<%= f.text_field :title, class: 'form-control', hide_label: true %>
		</div>
	</div>

	<div class="form-group">
		<label for="price" class="control-label col-sm-3">Price</label>
		<div class="col-sm-9">
			<%= f.text_field :price, class: 'form-control', hide_label: true %>
		</div>
	</div>
	<div class="form-group">
		<label for="description" class="control-label col-sm-3">Description</label>
		<div class="col-sm-9">
			<%= f.text_field :description, class: 'form-control', hide_label: true %>
		</div>
	</div>

	<div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control"  %>
  </div>

  	<div class="form-group">
    <%= f.select :category, [['USB', 1], ['Stationary', 2], ['The Schoolyard', 3], ['Bags', 4]] %><br>



	<div class="form-group actions control-group">
		<div class="col-sm-offset-3">
			<%= f.submit class: "btn btn-primary" %>
		</div>
	</div>

<% end %>

app/views/products/edit.html.erb
<h1>products#edit</h1>

<div class="container">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/products/new.html.erb
<h1>products#new</h1>
<div class="space">
</div>
<div class="container newprod">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<h1>products#show</h1>



<p>
 
  <%= @product  %>
</p>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>